// Feature: temple-data-expansion, Property 5: Arrival/departure times strictly increasing
//
// Validates: Requirements 5.4, 6.5
//
// For any day plan with N >= 2 temples generated by ItineraryGenerator,
// the sequence of arrival and departure times must be strictly monotonically
// increasing: arrival[i] < departure[i] < arrival[i+1] for all valid i.

import 'dart:math';
import 'package:flutter_test/flutter_test.dart';
import 'package:yatra_app/models/temple_model.dart';
import 'package:yatra_app/services/itinerary_generator.dart';

void main() {
  // ── Helpers ────────────────────────────────────────────────────────────────

  /// Parse "HH:MM AM/PM" to total minutes since midnight.
  int _parseMinutes(String time) {
    final parts = time.split(' ');
    final tp = parts[0].split(':');
    int h = int.parse(tp[0]);
    final m = int.parse(tp[1]);
    final isPm = parts[1] == 'PM';
    if (isPm && h != 12) h += 12;
    if (!isPm && h == 12) h = 0;
    return h * 60 + m;
  }

  /// Build a temple at a given lat offset (controls travel distance).
  Temple _makeTemple(String id, double lat) {
    return Temple(
      id: id,
      name: 'Temple $id',
      placeId: 'place_$id',
      latitude: lat,
      longitude: 78.47,
      address: '',
      distinctiveFeatures: '',
      festivals: '',
      prasadamInfo: '',
      darshanTimings: '',
      rating: 4.0, // <= 4.5 → 30 min darshan
    );
  }

  // Feature: temple-data-expansion, Property 5: Arrival/departure times strictly increasing
  group('Property 5 — Itinerary arrival/departure times are monotonically increasing', () {
    final rng = Random(7);

    test(
      '100 random 2–8 temple day plans have strictly increasing arrival/departure times',
      () {
        for (int iteration = 0; iteration < 100; iteration++) {
          final n = 2 + rng.nextInt(7); // 2–8 temples

          // Space temples 0.1° apart in latitude (~11 km each → ~16 min travel at 40 km/h)
          final temples = List.generate(
            n,
            (i) => _makeTemple('t${iteration}_$i', 17.0 + i * 0.1),
          );

          // Random start hour 6–10 AM
          final startHour = 6 + rng.nextInt(5);

          final generator = ItineraryGenerator(
            availableTemples: temples,
            constraints: ItineraryConstraints(
              maxTemplesPerDay: n,
              travelMode: 'Car',
              startHour: startHour,
              startMinute: 0,
            ),
          );

          final itinerary = generator.generate();

          expect(
            itinerary.dayPlans,
            isNotEmpty,
            reason: 'Iteration $iteration: expected at least one day plan',
          );

          final visits = itinerary.dayPlans[0].visits;

          expect(
            visits.length,
            greaterThanOrEqualTo(2),
            reason: 'Iteration $iteration: expected at least 2 visits',
          );

          for (int i = 0; i < visits.length; i++) {
            final arrival = _parseMinutes(visits[i].arrivalTime);
            final departure = _parseMinutes(visits[i].departureTime);

            // arrival[i] < departure[i]
            expect(
              departure,
              greaterThan(arrival),
              reason:
                  'Iteration $iteration, visit $i: '
                  'departure (${visits[i].departureTime}) must be after '
                  'arrival (${visits[i].arrivalTime})',
            );

            // departure[i] < arrival[i+1]
            if (i < visits.length - 1) {
              final nextArrival = _parseMinutes(visits[i + 1].arrivalTime);
              expect(
                nextArrival,
                greaterThan(departure),
                reason:
                    'Iteration $iteration, visit $i→${i + 1}: '
                    'next arrival (${visits[i + 1].arrivalTime}) must be after '
                    'departure (${visits[i].departureTime})',
              );
            }
          }
        }
      },
    );

    test('3-temple day has strictly increasing times (concrete example)', () {
      final temples = [
        _makeTemple('a', 17.0),
        _makeTemple('b', 17.1),
        _makeTemple('c', 17.2),
      ];

      final generator = ItineraryGenerator(
        availableTemples: temples,
        constraints: const ItineraryConstraints(
          maxTemplesPerDay: 3,
          travelMode: 'Car',
          startHour: 8,
          startMinute: 0,
        ),
      );

      final itinerary = generator.generate();
      final visits = itinerary.dayPlans[0].visits;

      expect(visits.length, equals(3));

      for (int i = 0; i < visits.length; i++) {
        final arrival = _parseMinutes(visits[i].arrivalTime);
        final departure = _parseMinutes(visits[i].departureTime);
        expect(departure, greaterThan(arrival),
            reason: 'Visit $i: departure must be after arrival');
        if (i < visits.length - 1) {
          final nextArrival = _parseMinutes(visits[i + 1].arrivalTime);
          expect(nextArrival, greaterThan(departure),
              reason: 'Visit $i→${i + 1}: next arrival must be after departure');
        }
      }
    });
  });
}
